spring.datasource.url: jdbc:mysql://localhost:3306/yllu_tst
spring.datasource.username: root
spring.datasource.password: wolsvagan
spring.jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl